name: Build and Test

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
        - uses: actions/checkout@v2
        - name: Setup .NET Core SDK
          uses: actions/setup-dotnet@v1.4.0
          with:
            # SDK version to use. Example: 2.2.104
            dotnet-version: 3.1.104
        - name: Build with dotnet
          run: dotnet build --configuration Release OpenXmlApi/OfficeDocumentsApi.sln
        - name: Test with dotnet
          run: dontnet test --configuration Release OpenXmlApi/OfficeDocumentsApi.sln
