name: Build and Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
#    defaults:
#      run:
#        working-directory: OpenXmlApi

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up .NET SDK from global.json
        uses: actions/setup-dotnet@v4
        with:
          global-json-file: global.json
          
      - name: Restore dependencies
        run: dotnet restore OfficeDocuments.sln

      - name: Build project
        run: dotnet build OfficeDocuments.sln --no-restore --configuration Release

      - name: Run tests
        run: dotnet test OfficeDocuments.sln --no-build --verbosity normal