name: Build and Test

on: 
  push:
    branches:
      - ! test-release

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v2
        - name: Setup .NET Core SDK
          uses: actions/setup-dotnet@v1.4.0
          with:
            dotnet-version: 3.1.101
        - name: Build with dotnet
          run: dotnet build --configuration Release OpenXmlApi/OfficeDocumentsApi.sln
        - name: Test with dotnet
          run: dotnet test --configuration Release OpenXmlApi/OfficeDocumentsApi.sln
